import { getRoutePath } from "../utils/routeUtils"

const sideMenuDoctor = [
    {
        id: "tab-dashboard",
        icon: "dashboard",
        iconType: "material-icon",
        text: "Dashboard",
        path: getRoutePath( "doctor" ),
    },
    {
        id: "tab-recordings",
        icon: "mic",
        iconType: "material-icon",
        text: "Recordings",
        path: getRoutePath( "doctor.recordings" ),
    },
    {
        id: "tab-patients",
        icon: "people",
        iconType: "material-icon",
        text: "Patients",
        childState: false,
        children: [
            {
                id: "tab-all-patients",
                parentId: "tab-patients",
                icon: "fiber_manual_record",
                iconType: "material-icon",
                text: "All Patients",
                path: getRoutePath( "doctor.patients.list" ),
            },
            {
                id: "tab-add-patient",
                parentId: "tab-patients",
                icon: "fiber_manual_record",
                iconType: "material-icon",
                text: "Add New Patient",
                path: getRoutePath( "doctor.patients.add" ),
            },
        ],
    },
    {
        id: "tab-appointments",
        icon: "Appointments.svg",
        iconType: "image",
        text: "Appointments",
        childState: false,
        children: [
            {
                id: "tab-all-appointments",
                parentId: "tab-appointments",
                icon: "fiber_manual_record",
                iconType: "material-icon",
                text: "All Appointments",
                path: getRoutePath( "doctor.appointments.list" ),
            },
            {
                id: "tab-add-appointment",
                parentId: "tab-appointments",
                icon: "fiber_manual_record",
                iconType: "material-icon",
                text: "Add New Appointment",
                path: getRoutePath( "doctor.appointments.add" ),
            },
        ],
    },
    {
        id: "tab-consultation",
        icon: "local_hospital",
        iconType: "material-icon",
        text: "Consultation",
        path: getRoutePath( "doctor.consultation.efax" ),
    },
    {
        id: "tab-prescriptions",
        icon: "description",
        iconType: "material-icon",
        text: "Prescriptions",
        childState: false,
        children: [
            {
                id: "tab-all-prescriptions",
                parentId: "tab-prescriptions",
                icon: "fiber_manual_record",
                iconType: "material-icon",
                text: "All Prescriptions",
                path: getRoutePath( "doctor.prescriptions.list" ),
            },
            {
                id: "tab-add-prescription",
                parentId: "tab-prescriptions",
                icon: "fiber_manual_record",
                iconType: "material-icon",
                text: "Create New",
                path: getRoutePath( "doctor.prescriptions.add" ),
            },
        ],
    },
    {
        id: "tab-labs-radiology",
        icon: "science",
        iconType: "material-icon",
        text: "Labs/Radiology",
        path: getRoutePath( "doctor.labs_radiology" ),
    },
    {
        id: "tab-chat_support",
        icon: "chat",
        iconType: "material-icon",
        text: "AI Support",
        childState: false,
        children: [
            {
                id: "tab-ai-visit-notes",
                parentId: "tab-chat_support",
                icon: "fiber_manual_record",
                iconType: "material-icon",
                text: "AI Visit Notes",
                path: getRoutePath( "doctor.ai_supports.visit_notes" ),
            },
            {
                id: "tab-ai-chat-support",
                parentId: "tab-chat_support",
                icon: "fiber_manual_record",
                iconType: "material-icon",
                text: "AI Chat Support",
                path: getRoutePath( "doctor.ai_supports.chat" ),
            },
            // {
            //     id: "tab-chat-with-agent",
            //     parentId: "tab-chat_support",
            //     icon: "fiber_manual_record",
            //     iconType: "material-icon",
            //     text: "Chat With Agent",
            //     path: getRoutePath( "doctor.ai_supports.chat_with_agent" ),
            // },
            {
                id: "tab-email-support",
                parentId: "tab-chat_support",
                icon: "fiber_manual_record",
                iconType: "material-icon",
                text: "Email Support",
                path: getRoutePath( "doctor.ai_supports.email" ),
            },
        ],
    },
    {
        id: "tab-doctors",
        icon: "medical_services",
        iconType: "material-icon",
        text: "Consultant",
        path: getRoutePath( "doctor.doctors" ),
    },
    {
        id: "tab-super-bills",
        icon: "receipt",
        iconType: "material-icon",
        text: "Super Bills",
        path: getRoutePath( "doctor.super_bills" ),
    },
    {
        id: "tab-customizations",
        icon: "tune",
        iconType: "material-icon",
        text: "Customizations",
        path: getRoutePath( "doctor.customizations.color_theme" ),
    },
    {
        id: "tab-compl-security",
        icon: "lock",
        iconType: "material-icon",
        text: "Compl. & Security",
        path: "#",
        childState: false,
        children: [
            {
                id: "tab-hippa-compliance",
                parentId: "tab-compl-security",
                icon: "fiber_manual_record",
                iconType: "material-icon",
                text: "HIPPA Compliance",
                path: getRoutePath( "doctor.hippa_compliance" ),
            },
            {
                id: "tab-user-access-control",
                parentId: "tab-compl-security",
                icon: "fiber_manual_record",
                iconType: "material-icon",
                text: "User Access Control",
                path: getRoutePath( "doctor.user_access_control" ),
            },
        ],
    },
]
export default sideMenuDoctor